layout_spectrum: 0.08834586
color:
  saturation: 0.4580201
  lightness: 0.9191729
  brandStrength: 0.5100251
  brandColors:
    - '#0B0F28'
    - '#CFCFC6'
    - '#91786F'
    - '#392F27'
    - '#8899F2'
  rhythmicContrast: 0.5557644
typography_spectrum: 0.1510025
name: William Larsten
